"""empty message

Revision ID: 128422b733d5
Revises: 4755bf6a349a
Create Date: 2025-06-30 18:49:29.022765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128422b733d5'
down_revision = '4755bf6a349a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('street_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='address_pkey')
    )
    op.drop_table('token_blocked_list')
    # ### end Alembic commands ###
